language: c++

os:
    - linux
    - osx

compiler:
    - gcc

install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gfortran libopenblas-dev liblapack-dev ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake . ; fi
    # On OSX we have to avoid the Clang compiler
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (brew install gcc || brew link --overwrite gcc) ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libomp ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake . -DCMAKE_CXX_COMPILER=g++-8 ; fi
    - sudo make install

script:
    - cd examples/
    - mess mess.inp
    - cat mess.out
    - messpf messpf.inp
    - cat messpf.dat
    - messabs messabs.inp
    - cat messabs.out
    - cd ..
