language: c++

dist: xenial

os: linux

compiler: gcc

install:
    - sudo apt-get install libopenblas-dev liblapack-dev
    # Install SLATEC the hacky way
    - sudo apt-get install gfortran
    - wget http://www.netlib.org/slatec/slatec_src.tgz
    - tar -zxvf slatec_src.tgz
    - cd src
    - rm bvder.f  bvsup.f  dbvder.f  dbvsup.f  drkfab.f  rkfab.f bvpor.f dbvpor.f  dexbvp.f  exbvp.f
    - gfortran -shared -O2 ./*.f -o libslatec.so -fPIC
    - sudo mv libslatec.so /usr/lib/.
    - cd ..
    # Install MESS without MPACK
    - cmake .
    - sudo make install

script:
    - cd examples/
    - mess mess.inp
    - cat mess.out
    - messpf messpf.inp
    - cat messpf.dat
    - messabs messabs.inp
    - cat messabs.out
    - cd ..
