name: mess-env

channels:
    - auto-mech
    - conda-forge

dependencies:
    - auto-mech::slatec
    - auto-mech::mpack
    - conda-forge::cmake=3.21.3
    - conda-forge::gcc_linux-64=7.5.0
    - conda-forge::gxx_linux-64=7.5.0
    - conda-forge::gsl=2.7
    - conda-forge::blas
    - conda-forge::openblas # [linux]
