package:
    name: mess
    version: 0.1.0

source:
    path: .

requirements:
    build:
        - cmake
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
    host:
        - blas
        - openblas # [linux]
    run:
        - blas
        - openblas # [linux]
