# cmd: conda build . -c auto-mech
package:
    name: mess
    version: "1.10.0"

source:
    path: .

requirements:
     build:
         - cmake
         - gcc_linux-64
         - gfortran_linux-64
         - blas
         - openblas # [linux]
         - slatec
         - mpack
     run:
         - cmake
         - gcc_linux-64
         - gfortran_linux-64
         - blas
         - openblas # [linux]
         - slatec
         - mpack
