# cmd: conda build . -c auto-mech
package:
    name: mess
    version: "1.5.0"

source:
    path: .

requirements:
    build:
        - cmake
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - blas
        - openblas # [linux]
        - slatec
        - mpack
    run:
        - cmake
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - blas
        - openblas # [linux]
        - slatec
        - mpack
