# cmd: conda build . -c auto-mech -c conda-forge
package:
    name: mess
    version: "2.2.0"

source:
    path: .

requirements:
     build:
         - auto-mech::slatec
         - auto-mech::mpack
         - conda-forge::cmake=3.20.2
         - conda-forge::gcc_linux-64=7.5.0
         - conda-forge::gfortran_linux-64=7.5.0
         - conda-forge::blas
         - conda-forge::openblas # [linux]
         - conda-forge::gsl=2.7
     run:
         - auto-mech::slatec
         - auto-mech::mpack
         - conda-forge::cmake=3.20.2
         - conda-forge::gcc_linux-64=7.5.0
         - conda-forge::gfortran_linux-64=7.5.0
         - conda-forge::openblas # [linux]
         - conda-forge::gsl=2.7
