# cmd: conda build . -c pacchem
package:
    name: mess
    version: "0.1.6"

source:
    path: .

requirements:
    build:
        - cmake
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - blas
        - openblas # [linux]
        - slatec
        - mpack
    run:
        - cmake
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - blas
        - openblas # [linux]
        - slatec
        - mpack
