version: 2
jobs:
    build-ubuntu:
        docker:
            - image: circleci/buildpack-deps:18.04
        steps:
          - checkout
          - run:
              name: Install dependencies and build
              command: |
                  sudo apt-get install gcc gfortran cmake libopenblas-dev
                  echo 'export BLAS=/usr/lib/x86_64-linux-gnu/openblas/libblas.so' >> $BASH_ENV
                  echo 'export LAPACK=/usr/lib/x86_64-linux-gnu/openblas/liblapack.so' >> $BASH_ENV
                  source $BASH_ENV
                  cmake . -DBLAS_LIBRARIES=${BLAS} -DLAPACK_LIBRARIES=${LAPACK}
                  sudo make install
          - run:
              name: Run examples
              command: |
                  cd examples/
                  mess mess.inp
                  cat mess.out
                  messpf messpf.inp
                  cat messpf.dat
                  messabs messabs.inp
                  cat messabs.out
                  messsym messsym.inp
                  cd ..
workflows:
    version: 2
    build-all:
        jobs:
            - build-ubuntu
