name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up C++ and Fortran
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ gfortran make cmake

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build Project
      run: |
        cd build
        make -j2 # Using 2 cores for the CI build 